### ISSUE TITLE
Lesson 3 - Missing prod-debug.js, debugger.js, and test.webpack.config.js in 'after' version or folder

### ISSUE THREAD

**Issue by eastmaels** [koii-network/ezsandbox#104]
When running tasks locally, the default steps when running task is:

`npm run prod-debug`

Based on package.json, this runs the following task, which points to prod-debug.js

```
  "scripts": {
    ...
    "prod-debug": "nodemon --ignore 'dist/*' prod-debug.js",
    ...
  },
```

However, upon checking the codes, the after version of the codes does not contain the files `prod-debug.js` as well as  the related files `debugger.js` and `test.webpack.config.js`. 
Although the project will run, I think it will save future contributors/developers less headache that the example project does not update successfully because of the configurations done when 'prod-debug.js` is available.

#### References
* Lesson 3 - after codes link:
https://github.com/koii-network/ezsandbox/tree/main/Lesson%203/simple-crawler/after

![image](https://github.com/user-attachments/assets/6de72eae-83a2-4588-b7dd-c90b70855900)

**Comment by labrocadabro** [comment]
Thank you! My hope is to eventually restructure so that

1. We're developing a single task over the course of the lessons
2. We're cloning from the task template rather than keeping copies of it in this repo (which then need to all be kept in sync with both each other and the template)
3. Each lesson will contain only the `task` folder with the changes that were made in that lesson.

But for now, thank you so much for all your work reviewing the tasks and spotting bugs!
